/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoshilo;

import javax.swing.DefaultListModel;

/**
 *
 * @author TELMEX
 */
public class Ejercicio2Frame extends javax.swing.JFrame {
static DefaultListModel dl= new DefaultListModel();   
    /**
     * Creates new form Ejercicio2Class
     */
    public Ejercicio2Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caja1 = new javax.swing.JTextField();
        caja4 = new javax.swing.JTextField();
        caja2 = new javax.swing.JTextField();
        caja3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        main = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setViewportView(main);

        jButton2.setText("Activar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(caja1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(caja2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(caja3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(caja4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caja1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caja4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caja2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caja3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       Ejercicio2Class ob1= new Ejercicio2Class ("Sub_PROCESO1 ");
        Ejercicio2Class ob2= new Ejercicio2Class ("Sub_PROCESO2 ");
         Ejercicio2Class ob3= new Ejercicio2Class ("Sub_PROCESO3 ");
          Ejercicio2Class ob4= new Ejercicio2Class ("Sub_PROCESO4 ");
 
          
         //System.out.println("Termina main");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
    
              
              String texto1 = ob1.texto1;
                String texto2 = ob2.texto2;
                String texto3 = ob3.texto3;
                String texto4 = ob4.texto4;
                caja1.setText(texto1);
                caja2.setText(texto2);
                caja3.setText(texto3);
                caja4.setText(texto4);
                for (int i = 0; i <=7; i++) {
                    
                    dl.add(i,i);
             main.setModel(dl);
                }  
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
         
       Ejercicio2Class ob1= new Ejercicio2Class ("Sub_PROCESO1 ");
        Ejercicio2Class ob2= new Ejercicio2Class ("Sub_PROCESO2 ");
         Ejercicio2Class ob3= new Ejercicio2Class ("Sub_PROCESO3 ");
          Ejercicio2Class ob4= new Ejercicio2Class ("Sub_PROCESO4 ");
 
          
         //System.out.println("Termina main");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
    
              new Ejercicio2Frame().setVisible(true);
              String texto1 = ob1.texto1;
                String texto2 = ob2.texto2;
                String texto3 = ob3.texto3;
                String texto4 = ob4.texto4;
                caja1.setText(texto1);
                caja2.setText(texto2);
                caja3.setText(texto3);
                caja4.setText(texto4);
                for (int i = 0; i <=7; i++) {
                    
                    dl.add(i,i);
             main.setModel(dl);
                }  
            }
        });
    }
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField caja1;
    public static javax.swing.JTextField caja2;
    public static javax.swing.JTextField caja3;
    public static javax.swing.JTextField caja4;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JList<String> main;
    // End of variables declaration//GEN-END:variables
}
